"""
RoundTable API Routes

POST /v1.0/round-table/generate - Generate round_table illustration with LLM
Auto-generated by Illustration Builder.
"""

import logging
import time
import re
from pathlib import Path
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from typing import Optional, Dict, Any, List

from app.llm_services.round_table_generator import get_generator

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/v1.0/round-table", tags=["round_table"])


class RoundTableGenerateRequest(BaseModel):
    """Request model for Round Table generation"""
    num_elements: int = Field(default=5, ge=1, le=8, description="Number of elements")
    topic: str = Field(..., description="Main topic for the illustration")
    context: Optional[Dict[str, Any]] = Field(default={}, description="Additional context")
    target_points: Optional[List[str]] = Field(default=None, description="Key points to include")
    tone: str = Field(default="professional", description="Writing tone")
    audience: str = Field(default="general", description="Target audience")
    theme: str = Field(default="professional", description="Visual theme")
    size: str = Field(default="medium", description="Size preset")
    validate_constraints: bool = Field(default=True, description="Validate character limits")
    presentation_id: Optional[str] = Field(default=None, description="Presentation ID for tracking")
    slide_id: Optional[str] = Field(default=None, description="Slide ID for tracking")


class RoundTableGenerateResponse(BaseModel):
    """Response model for Round Table generation"""
    success: bool
    html: Optional[str] = None
    infographic_html: Optional[str] = None  # Alias for Layout Service compatibility
    metadata: Optional[Dict[str, Any]] = None
    generated_content: Optional[Dict[str, Any]] = None
    character_counts: Optional[Dict[str, int]] = None
    validation: Optional[Dict[str, Any]] = None
    generation_time_ms: Optional[int] = None
    error: Optional[str] = None


@router.post("/generate", response_model=RoundTableGenerateResponse)
async def generate_round_table(request: RoundTableGenerateRequest):
    """
    Generate Round Table illustration with LLM-powered content.

    Workflow:
    1. Validate element count (1-8)
    2. Call Gemini to generate element content with character constraints
    3. Validate character counts
    4. Fill HTML template with generated content
    5. Return complete HTML
    """
    start_time = time.time()

    try:
        logger.info(
            f"Generating {request.num_elements}-element round_table: '{request.topic}'"
        )

        # Get generator
        generator = get_generator()

        # Generate content via LLM
        gen_result = await generator.generate_round_table_data(
            num_elements=request.num_elements,
            topic=request.topic,
            context=request.context or {},
            target_points=request.target_points,
            tone=request.tone,
            audience=request.audience,
            validate_constraints=request.validate_constraints
        )

        if not gen_result["success"]:
            raise HTTPException(
                status_code=500,
                detail=f"Content generation failed: {gen_result.get('error')}"
            )

        generated_content = gen_result["content"]

        # Determine template file
        template_file = f"{request.num_elements}.html"

        # Load template directly (same pattern as star_diagram_routes.py)
        template_path = Path(__file__).parent.parent.parent / "templates" / "round_table" / template_file

        try:
            with open(template_path, 'r') as f:
                template_html = f.read()
        except FileNotFoundError:
            raise HTTPException(
                status_code=404,
                detail=f"Template not found: {template_path}"
            )

        # Fill template with generated content
        filled_html = template_html

        logger.info(f"Filling template with {len(generated_content)} fields")
        logger.info(f"Generated content keys: {sorted(generated_content.keys())}")

        for key, value in generated_content.items():
            placeholder = f"{{{key}}}"
            count = template_html.count(placeholder)
            if count > 0:
                logger.info(f"Replacing {placeholder} ({count} occurrences)")
            filled_html = filled_html.replace(placeholder, str(value))

        # Check for remaining placeholders
        remaining = re.findall(r'\{[^}]+\}', filled_html)
        if remaining:
            logger.warning(f"Remaining unfilled placeholders: {remaining[:10]}")

        # Calculate total generation time
        total_time = int((time.time() - start_time) * 1000)

        # Build response
        response = RoundTableGenerateResponse(
            success=True,
            html=filled_html,
            infographic_html=filled_html,  # Layout Service compatibility
            metadata={
                "num_elements": request.num_elements,
                "template_file": template_file,
                "theme": request.theme,
                "size": request.size,
                "topic": request.topic,
                "code_version": "v1.0.0-auto-generated",
                **gen_result.get("metadata", {})
            },
            generated_content=generated_content,
            character_counts=gen_result["character_counts"],
            validation=gen_result["validation"],
            generation_time_ms=total_time
        )

        logger.info(
            f"Successfully generated {request.num_elements}-element round_table "
            f"in {total_time}ms"
        )

        return response

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error generating round_table: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Internal server error: {str(e)}"
        )


@router.get("/info")
async def get_round_table_info():
    """Get information about this illustration type"""
    return {
        "name": "round_table",
        "display_name": "Round Table",
        "description": "8 point round table",
        "keywords": ['round_table', '8 points'],
        "default_elements": 5,
        "element_range": {"min": 1, "max": 8},
        "endpoints": {
            "generate": "POST /v1.0/round-table/generate"
        }
    }
