#!/bin/bash
# Test script for round_table illustration type
# Auto-generated by Illustration Builder

set -e

BASE_URL="${BASE_URL:-http://localhost:8000}"
LAYOUT_URL="${LAYOUT_URL:-https://web-production-f0d13.up.railway.app}"
OUTPUT_DIR="test_outputs"

mkdir -p "$OUTPUT_DIR"

echo "========================================"
echo "Testing Round Table endpoint"
echo "========================================"
echo ""

# Test 1: Generate illustration
echo "Test 1: Generate Round Table..."
RESPONSE=$(curl -s -X POST "$BASE_URL/v1.0/round-table/generate" \
  -H "Content-Type: application/json" \
  -d '{
    "num_elements": 5,
    "topic": "Test Topic for Round Table",
    "tone": "professional",
    "audience": "general"
  }')

# Check success
SUCCESS=$(echo "$RESPONSE" | jq -r '.success')
if [ "$SUCCESS" != "true" ]; then
    echo "ERROR: Generation failed"
    echo "$RESPONSE" | jq .
    exit 1
fi

echo "SUCCESS: Round Table generated"

# Save HTML for inspection
HTML=$(echo "$RESPONSE" | jq -r '.html')
echo "$HTML" > "$OUTPUT_DIR/round_table_test.html"
echo "HTML saved to $OUTPUT_DIR/round_table_test.html"

# Show character counts
echo ""
echo "Character counts:"
echo "$RESPONSE" | jq '.character_counts'

# Show validation
echo ""
echo "Validation:"
echo "$RESPONSE" | jq '.validation'

echo ""
echo "========================================"
echo "All tests passed!"
echo "========================================"
