"""
StarDiagram Validator

Validates content constraints for star_diagram illustrations.
Auto-generated by Illustration Builder.
"""

import json
import logging
from pathlib import Path
from typing import Dict, Any, Tuple, List

logger = logging.getLogger(__name__)


class StarDiagramValidator:
    """Validates star_diagram content against character constraints"""

    def __init__(self):
        self.constraints = self._load_constraints()

    def _load_constraints(self) -> Dict:
        """Load constraints from JSON file"""
        path = Path(__file__).parent.parent / "variant_specs" / "star_diagram_constraints.json"
        try:
            with open(path) as f:
                return json.load(f)
        except FileNotFoundError:
            logger.warning(f"Constraints file not found: {path}")
            return {}

    def get_constraints_for_variant(self, num_elements: int) -> Dict:
        """Get constraints for a specific variant"""
        key = f"star_diagram_{num_elements}"
        return self.constraints.get(key, {})

    def validate_content(self, content: Dict, num_elements: int) -> Tuple[bool, List[str]]:
        """
        Validate generated content against constraints.

        Returns:
            Tuple of (is_valid, list_of_violations)
        """
        constraints = self.get_constraints_for_variant(num_elements)
        violations = []

        def check_field(field_name: str, value: str, limits: Dict):
            if not isinstance(value, str):
                return
            length = len(value)
            min_len = limits.get("min", 0)
            max_len = limits.get("max", 999)
            if length < min_len or length > max_len:
                violations.append(
                    f"{field_name}: {length} chars (expected {min_len}-{max_len})"
                )

        for element_id, element_constraints in constraints.items():
            if isinstance(element_constraints, dict):
                for field, limits in element_constraints.items():
                    if isinstance(limits, dict) and "min" in limits:
                        field_key = f"{element_id}_{field}" if not field.startswith(element_id) else field
                        if field_key in content:
                            check_field(field_key, content[field_key], limits)

        return len(violations) == 0, violations

    def get_character_counts(self, content: Dict, num_elements: int) -> Dict:
        """Get character counts for all string fields in content"""
        return {k: len(v) for k, v in content.items() if isinstance(v, str)}


# Global validator instance
_validator: StarDiagramValidator = None


def get_validator() -> StarDiagramValidator:
    """Get or create the global validator instance"""
    global _validator
    if _validator is None:
        _validator = StarDiagramValidator()
    return _validator
